[general]
API_KEY="KG3ITSUFXJLCN25G3ZX9MIFUXBUZLQ7SNB1YJV6TSKL1DANZA4NSKYHOXLOZH0HA"
BASE_URL="https://connect.avadatatrust.com/api/v1/data/assets/search"
ASSET_URL="https://connect.avadatatrust.com/api/v1/data/assets"
LINEAGE_URL="https://connect.avadatatrust.com/api/v1/data/catalog/lineage/manual_lineage"
DQ_URL="https://connect.avadatatrust.com/api/v1/data/monitors"
LOGO_URL="https://raw.githubusercontent.com/samuvelisaac/DTS/main/ascendion_logo.jpg"
API_KEY_P1 = "eyJraWQiOiIwODMwYWI0MS05MzM5LTQwZTgtODhhZC1iMGQ3NDY1ZDAyM2MiLCJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2FzY2VuZGlvbi5jb20iLCJpZGVudGlmaWVyIjoiYXZhIy0qZ3B0IiwibmFtZSI6Imdsb2JhbCBhY2Nlc3MiLCJlbWFpbCI6Imdsb2JhbC5hY2Nlc3NrZXlAYXNjZW5kaW9uLmNvbSIsImlhdCI6MTcyNjc1MDk3MSwiZXhwIjoxNzY2MTAyNDAwfQ.ZvoB40XIXqWPfKtvCvLOCk2mSiOJ6cc11vSkSoTgu2I4q0TZ87ChXFGh9f6iJjyY7C2QaFJ5NzsUeq83g6mc_w"
API_URL_P1 = "https://avaplus-internal.avateam.io/force/platform/pipeline/api/v1/execute"
GitHub_Token = "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"
Repository_Owner = "samuvelisaac"
Repository_Name = "DTS"
Folder_Path = "AAVA DTS Ally"
