[general]
API_KEY = "KG3ITSUFXJLCN25G3ZX9MIFUXBUZLQ7SNB1YJV6TSKL1DANZA4NSKYHOXLOZH0HA"
BASE_URL = "https://connect.avadatatrust.com/api/v1/data/assets/search"
ASSET_URL = "https://connect.avadatatrust.com/api/v1/data/assets"
LINEAGE_URL = "https://connect.avadatatrust.com/api/v1/data/catalog/lineage/manual_lineage"
DQ_URL = "https://connect.avadatatrust.com/api/v1/data/monitors"
LOGO_URL = "https://raw.githubusercontent.com/samuvelisaac/DTS/main/ascendion_logo.jpg"
